const defaultOpportunities = [
  {
    title: 'Summer Beauty Campaign 2026',
    description:
      'Looking for beauty influencers to promote our new summer skincare line. Must create 3 Instagram reels and 2 stories showcasing the products in a natural, lifestyle setting. Products will be shipped for free.',
    brandName: 'GlowUp Cosmetics',
    category: 'beauty',
    platforms: ['instagram'],
    budget: 15000,
    budgetMin: 10000,
    budgetMax: 20000,
    location: 'Mumbai, India',
    requirements: 'Min 50K followers, beauty niche, high engagement rate',
    deadline: new Date('2026-08-30'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Fitness App Launch Promotion',
    description:
      'We are launching a new AI-powered fitness app and need fitness influencers to create workout content using the app. Deliverables: 2 YouTube videos + 4 Instagram posts with app demo.',
    brandName: 'FitTech Labs',
    category: 'fitness',
    platforms: ['instagram', 'youtube'],
    budget: 25000,
    budgetMin: 20000,
    budgetMax: 35000,
    location: 'Bangalore, India',
    requirements: 'Fitness niche, 100K+ followers, video content experience',
    deadline: new Date('2026-09-15'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Street Food Series Sponsorship',
    description:
      'Create a 5-part Instagram reel series exploring street food across Indian cities while featuring our brand. Each reel should be 60-90 seconds with authentic storytelling.',
    brandName: 'Zomato Kitchen',
    category: 'food',
    platforms: ['instagram', 'youtube'],
    budget: 30000,
    budgetMin: 25000,
    budgetMax: 40000,
    location: 'Delhi, India',
    requirements: 'Food niche, engaging storytelling, min 75K followers',
    deadline: new Date('2026-08-15'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Tech Gadget Review Partnership',
    description:
      'Review our latest wireless earbuds and smart watch on your YouTube channel. Honest reviews encouraged. We provide the products + compensation.',
    brandName: 'NovaTech India',
    category: 'tech',
    platforms: ['youtube'],
    budget: 20000,
    budgetMin: 15000,
    budgetMax: 25000,
    location: 'Hyderabad, India',
    requirements: 'Tech reviewer, min 50K YouTube subscribers, quality production',
    deadline: new Date('2026-09-01'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Sustainable Fashion Collection Drop',
    description:
      'Promote our new eco-friendly clothing line made from recycled materials. Looking for fashion-forward influencers who care about sustainability. 3 outfit posts + 1 reel required.',
    brandName: 'EcoThreads',
    category: 'fashion',
    platforms: ['instagram'],
    budget: 18000,
    budgetMin: 12000,
    budgetMax: 22000,
    location: 'Pune, India',
    requirements: 'Fashion niche, sustainability interest, aesthetic feed',
    deadline: new Date('2026-10-01'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Travel Vlog Series – Kerala Backwaters',
    description:
      'We are a premium resort looking for travel vloggers to create a 3-day travel vlog showcasing our property. Accommodation + food + compensation provided.',
    brandName: 'Kerala Luxe Resorts',
    category: 'travel',
    platforms: ['youtube', 'instagram'],
    budget: 45000,
    budgetMin: 35000,
    budgetMax: 60000,
    location: 'Kerala, India',
    requirements: 'Travel niche, cinematic video quality, 100K+ subscribers',
    deadline: new Date('2026-09-30'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Gaming Tournament Live Stream',
    description:
      'Host and stream our upcoming mobile gaming tournament on YouTube/Twitch. Promote to your audience with 1 week of pre-event content.',
    brandName: 'GameZone India',
    category: 'gaming',
    platforms: ['youtube', 'twitch'],
    budget: 35000,
    budgetMin: 25000,
    budgetMax: 50000,
    location: 'Gurgaon, India',
    requirements: 'Gaming niche, live streaming experience, 200K+ followers',
    deadline: new Date('2026-08-20'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Wellness & Yoga Brand Ambassador',
    description:
      'Become a 3-month brand ambassador for our organic wellness supplements. Monthly content: 2 posts + 3 stories + 1 reel featuring products in your wellness routine.',
    brandName: 'AyurVita Wellness',
    category: 'wellness',
    platforms: ['instagram'],
    budget: 50000,
    budgetMin: 40000,
    budgetMax: 65000,
    location: 'Rishikesh, India',
    requirements: 'Wellness/yoga niche, authentic lifestyle content, 80K+ followers',
    deadline: new Date('2026-10-15'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Music Festival Coverage',
    description:
      'Cover our upcoming indie music festival with behind-the-scenes content, artist interviews, and live performance snippets. Looking for music/entertainment influencers.',
    brandName: 'SoundWave Events',
    category: 'entertainment',
    platforms: ['instagram', 'youtube'],
    budget: 22000,
    budgetMin: 15000,
    budgetMax: 28000,
    location: 'Mumbai, India',
    requirements: 'Music/entertainment niche, event content experience',
    deadline: new Date('2026-09-10'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Online Education Platform Review',
    description:
      'Review our AI-powered learning platform and create educational content about effective online learning. Target: students and young professionals.',
    brandName: 'LearnSmart India',
    category: 'education',
    platforms: ['youtube', 'instagram'],
    budget: 12000,
    budgetMin: 8000,
    budgetMax: 18000,
    location: 'Chennai, India',
    requirements: 'Education/study niche, clear communication, 30K+ followers',
    deadline: new Date('2026-09-20'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Lifestyle Brand Collaboration – Home Decor',
    description:
      'Showcase our minimalist home decor collection in your home/apartment tour style content. Looking for lifestyle influencers with aesthetic sense.',
    brandName: 'UrbanNest Decor',
    category: 'lifestyle',
    platforms: ['instagram', 'youtube'],
    budget: 16000,
    budgetMin: 12000,
    budgetMax: 22000,
    location: 'Bangalore, India',
    requirements: 'Lifestyle niche, home/decor interest, aesthetic content',
    deadline: new Date('2026-10-30'),
    status: 'open',
    applicantCount: 0,
  },
  {
    title: 'Eco-Friendly Product Ambassador',
    description:
      'Long-term partnership to promote our range of sustainable, zero-waste everyday products. Monthly content creation with authentic product integration.',
    brandName: 'GreenLife India',
    category: 'sustainability',
    platforms: ['instagram', 'youtube'],
    budget: 28000,
    budgetMin: 20000,
    budgetMax: 35000,
    location: 'Delhi, India',
    requirements: 'Sustainability/eco niche, genuine passion for environment, 50K+',
    deadline: new Date('2026-11-01'),
    status: 'open',
    applicantCount: 0,
  },
];

export default defaultOpportunities;
